# Generated by Django 5.1.3 on 2024-11-20 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heart_rate', models.FloatField()),
                ('snoring_rate', models.FloatField()),
                ('respiratory_rate', models.FloatField()),
                ('body_temperature', models.FloatField()),
                ('limb_movements', models.FloatField()),
                ('blood_oxygen', models.FloatField()),
                ('eye_movement', models.FloatField()),
                ('sleep_hours', models.FloatField()),
                ('result', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
